pipelines:
 - name: sleep_pipeline
   steps:
     - name: S_Bash_0023
       type: Bash
       execution:
         onExecute:
           - echo "curl GET ${pipelines_api_url}/projectIntegrations -H Authorization:apiToken ${builder_api_token}"
           - response=$(curl GET "${pipelines_api_url}/projectIntegrations" -H Authorization:"apiToken ${builder_api_token}")
           - tokenValue=$(echo $response | jq '.[] | select(.name == "i_GitHub_admin_test") | .formJSONValues | .[] | select(.label == "token") | .value')
           - echo $tokenValue
           - if [ $tokenValue != "********" ]; then exit 1; fi
           - integrationId=$(echo $response | jq '.[] | select(.name == "i_GitHub_admin_test") | .id')
           - response=$(curl GET "${pipelines_api_url}/projectIntegrations/${integrationId}" -H Authorization:"apiToken ${builder_api_token}")
           - tokenValue=$(echo $response | jq '.formJSONValues | .[] | select(.label == "token") | .value')
           - echo $tokenValue
           - if [ $tokenValue != "********" ]; then exit 1; fi
