pipelines:
- name: my_pipe
  decorators:
  - name: my_decorator
    execution:
      onStart:
      - echo "before step"
      onComplete:
      - echo "after step"
  steps:
  - name: step1
    type: MvnBuild
    decorators:
    - name: my_decorator
    execution:
      onStart: 
      - echo "starting step1"
      onComplete:
      - echo "completed step1"  
