pipelines:
 - name: sleep_pipeline
   configuration:
        environmentVariables:
          readOnly:
            WORLD: "world"
   steps:
     - name: S_Bash_0023
       type: Bash
       execution:
         onExecute:
           - echo "hello ${WORLD}"
           - echo $BUILDER_API_TOKEN
           - echo $builder_api_token
           - echo $pipelines_api_url
           - echo "curl GET ${pipelines_api_url}/projectIntegrations -H Authorization:apiToken ${builder_api_token}"
           - curl GET "${pipelines_api_url}/projectIntegrations" -H Authorization:"apiToken ${builder_api_token}"
