pipelines:
  - name: sleep_pipeline
    configuration:
          environmentVariables:
            readOnly:
              WORLD: "world"
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo "hello ${WORLD}"
            - sleep 5m
