pipelines:
- name: my_pipe
  decorators:
  - name: my_dec1
    execution:
      beforeOnStart:
      - echo "before start 2"
      afterOnStart:
      - echo "after start 2"
      beforeOnComplete:
      - echo "before complete 2"
      beforeOnSuccess:
      - echo "before success 2"
  - name: my_decorator
    execution:
      beforeOnStart:
      - echo "before start"
      afterOnStart:
      - echo "after start"
      beforeOnComplete:
      - echo "before complete"
      beforeOnSuccess:
      - echo "before success"
  steps:
  - name: step1
    type: Bash
    decorators:
      - name: my_decorator 
      - name: my_dec2
    execution:
      onStart: 
      - echo "on start"
      onComplete:
      - echo "on complete"  
