resources:
  - name: wwwGit
    type: GitRepo
    configuration:
      path: rahulnlb1/jfrog-sleep2
      gitProvider: Github
      branches:
        include: xxx
      files:
        include: \bwww\/.+\b

pipelines:
 - name: sleep_pipeline
   configuration:
        environmentVariables:
          readOnly:
            WORLD: "world"
   steps:
     - name: S_Bash_0023
       type: Bash
       configuration:
         inputResources:
              - name: wwwGit
       execution:
         onExecute:
           - echo "hello ${WORLD}"
