pipelines:
- name: my_pipe
  steps:
  - name: step1
    type: Bash
    decorators:
      - name: my_decorator 
      - name: my_dec1
    execution:
      onStart: 
      - echo "on start"
      onComplete:
      - echo "on complete"  
