pipelines:
 - name: sleep_pipeline
   configuration:
        environmentVariables:
          readOnly:
            WORLD: "world"
   steps:
     - name: S_Bash_0023
       type: Bash
       execution:
         onExecute:
           - ls -la
           - >-
             if [ -f "hello.txt" ]; then
               cat hello.txt
             else
               echo "hello world" >> hello.txt
             fi
           - add_cache_files hello.txt hello
