pipelines:
- name: my_pipe
  decorators:
  - name: my_decorator
    execution:
      onBeforeStart:
      - echo "before start"
      onAfterStart:
      - echo "after start"
      onBeforeComplete:
      - echo "before complete"
      onBeforeSuccess:
      - echo "before success"
  steps:
  - name: step1
    type: Bash
    decorators:
      - name: my_decorator  
    execution:
      onStart: 
      - echo "on start"
      onComplete:
      - echo "on complete"  
